### ISSUE TITLE
date-before script raises error in November

### ISSUE THREAD

**Issue by keighrim** [dbeniamine/todo.txt-vim#9] opened 2016-11-03 16:35 UTC
[https://github.com/dbeniamine/todo.txt-vim/blob/master/syntax/python/dateregex/dateregex/before.py#L47-L48](https://github.com/dbeniamine/todo.txt-vim/blob/master/syntax/python/dateregex/dateregex/before.py#L47-L48)

Here, `(11+1) % 12` raises value error when passed as the `month` argument for `date()` .
Plus, those lines no longer seem to be used, anyway.

**Comment by dbeniamine** [comment] 2016-11-04 10:32
I do not have troubles with a due date like `due:2016-11-16` for instance, can you give me a minimal todo.txt that triggers the error ?

I presume that a fix could consist in replacing the line you pointed by:

    if month == 11 :
        month = 1
    else:
        month = (int(month)+1)%12
    last_month_day = str((date(int(year), month, 1) + - date.resolution).day)

I think this code was written by @victal, maybe they can help.

**Comment by victal** [comment] 2016-11-04 11:39
Yeah, I just got this error yesterday as well... The problem is not with a due date in November, but it should show up when it _is_ November and you have any due date on a task.

It seems the order of operations is mixed up - changing the expression on line 47 to 
`int(month) % 12 + 1`
instead of 
`(int(month)+1)%12)` 
in order to get the next month should suffice (`11 % 12 + 1` instead of `(11 + 1) % 12`).

**Comment by dbeniamine** [comment] 2016-11-04 13:03
Thanks @victal I merged your fix !

**Closed** 2016-11-04 13:02 UTC
